"""First migration

Revision ID: 0d7ea4f7c35d
Revises: 241641b8fbde
Create Date: 2016-11-30 21:23:48.932628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7ea4f7c35d'
down_revision = '241641b8fbde'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
