"""First migration

Revision ID: 241641b8fbde
Revises: 
Create Date: 2016-11-30 21:04:35.718522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241641b8fbde'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_one',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_one_id'), 'model_one', ['id'], unique=False)
    op.create_table('model_two',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_two_id'), 'model_two', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_two_id'), table_name='model_two')
    op.drop_table('model_two')
    op.drop_index(op.f('ix_model_one_id'), table_name='model_one')
    op.drop_table('model_one')
    ### end Alembic commands ###
